# config.yaml
num_tiles: 4
sliding_cycle: 4
prompt_list: [ "A man wearing a stripe suit."]
seed_list: [42]
num_of_inference_steps: 28
remark: "New_RoPE"
output_folder: "./output/"
full_attn_step: [1,2]
full_attn_layer: [1, 2]
enable_profiler: False
curve_type: "hilbert"