# config.yaml
ratio_list: [0]
num_tiles: 4
sliding_cycle: 4
prompt_list: [ "lion" ]
seed_list: [42, 43, 44, 45, 46, 47, 48, 49, 50]
toma_variant: "local_stripe"
num_of_inference_steps: 28
remark: "New_RoPE"
merge_step_interval: 3
full_attn_step: []
full_attn_layer: []
output_folder: "/home/sz3684/diffusion/reorder_local_attention/diffusion_reorder/output/lora"