# config.yaml
ratio_list: [ 0 ]
num_tiles: 4
sliding_cycle: 4
prompt_list: [ "lion" ]
seed_list: [ 42 ]
num_of_inference_steps: 28
remark: "New_RoPE"
merge_step_interval: 3
full_attn_step: [ 1, 2 ]
full_attn_layer: [ 1, 3 ]
output_folder: "./output/lora_1024_4"
