# config.yaml

generation:
  seed_list: [42]
  num_of_inference_steps: 28
  output_folder: "./output/temp"

tiling:
  num_tiles: 4
  sliding_cycle: 4

attention:
  full_attn_step: []
  full_attn_layer: []

lora:
  enabled: true
  path: "./lora_weight/ckpt_1024_16/checkpoint-2817"
