cache_dir: null
curve_type: hilbert
enable_profiler: false
full_attn_layer: []
full_attn_step: []
guidance_scale: 1.0
height: 1024
method: masking
model_repo: black-forest-labs/FLUX.2-klein-9B
num_of_inference_steps: 10
num_tiles: 4
output_folder: ./output/
prompt_list:
- A beautiful landscape with mountains and a lake in the middle.
remark: flux2_hilberta
seed_list:
- 42
- 43
sliding_cycle: 4
width: 1024
